WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800

BOIDS_COUNT = 7
OBSTACLE_COUNT = 5

BOX_DIM = 40
OBSTACLE_DIM = 5
BLOCK_WIDTH = .2

DEFAULT_SPEED = 5
DEFAULT_FORCE = 5
DEFAULT_SEPARATION = 5
DEFAULT_ALIGNMENT = 5
DEFAULT_COHESION = 5
DEFAULT_BOUND = 5
DEFAULT_AVOID = 5
DEFAULT_NEIGHBOR_DIST = 5
